MDScreen:
    name: "welcome"
    BoxLayout:
        canvas:
            Color:
                rgb: 0x33 / 255.0, 0x99 / 255.0, 0x66/255.0
                #rgb: 
            Rectangle:
                size: self.size
        orientation: "vertical"
        Image:
            source:"moveby.png"
            pos_hint: {"center_x": .5,"center_y": .5}
            size_hint: .5, .5
            #size: 300,300